config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root controller: :articles, action: :index
  
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: { minimum: 5}
    validates :content, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  
  validates :email, presence: true
  validates :comment, presence: true
  validates :article, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'Article was successfully created.'
      redirect_to @article
    else
      flash[:error] = "Title and text can't be blank!"
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to @article
    else
      flash[:error] = "Title and text can't be blank!"
      render 'edit'
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    Comment.create(comment_params.merge!(article: article))
    redirect_to root_path
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_to root_path, notice: 'Your comment has been deleted'
    else
      redirect_to root_path, notice: comment.errors.full_messages.to_sentence
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:comment, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def button_text
        if controller.action_name == "new"
            return "Create Article"
        end
    end
end

app/views/articles/edit.html.erb
<% content_for :title, "Edit Article" %>

<h1>Edit Article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% content_for :title, "Articles" %>
<%= link_to 'New Article', new_article_path %>

<% if @articles.any? %>
    <% @articles.each do |article| %>
        <div id="<%= dom_id(article) %>">
            <div>
                <h1>
                    <%= article.title %>
                </h1>
                <%= link_to 'Show', article_path(article) %>
                <%= link_to 'Edit', edit_article_path(article) %>
            </div>
            <p>
                <%= article.content %>
            </p>

            <%= form_with url: article_comments_path(article), scope: :comment, remote: false do |f| %>
            <%= f.label :email, 'Your email' %>
            <%= f.text_field :email %>
            <%= f.label :comment %>
            <%= f.text_field :comment %>
            <%= f.submit 'Send comment' %>
            <% end %>

            <% article.comments.each do |comment| %>
            <p>
                <%= comment.comment %>
            </p>
            <p>
                <%= comment.email %> commented on
                <%= comment.created_at.to_date.to_formatted_s(:db) %>
            </p>
            <%= link_to 'Delete comment', article_comment_path(article, comment), method: :delete %>
            <% end %>
        </div>
    <% end %>
<% else %>
    <h1>There are no articles in the database..</h1>
<% end %>

app/views/articles/new.html.erb
<% content_for :title, "New Article" %>

<h1>New Article</h1>

<%= form_for :article, url: articles_path do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :content %><br>
        <%= form.text_area :content %>
    </p>
    <p>
        <%= form.submit button_text %>
    </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for :title, @article.title %>
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>
<p>
    <strong>Text:</strong>
    <%= @article.content %>
</p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
  <% end %>
  <%= yield %>
</body>

</html>

<!-- <p class="notice"><%= notice %></p> -->
<!-- <p class="alert"><%= alert %></p> -->